// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0XgEb9-4RDnt2JLL6BvY0OkgMTcgmQQE',
    appId: '1:299855360243:android:05c62bcf098b03a2bf8786',
    messagingSenderId: '299855360243',
    projectId: 'grocery-3b0f8',
    databaseURL: 'https://grocery-3b0f8-default-rtdb.firebaseio.com',
    storageBucket: 'grocery-3b0f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa50MXVb2rmXCoThrJwwfnz0UDq7hCVHY',
    appId: '1:299855360243:ios:2b1ee2997f4e160dbf8786',
    messagingSenderId: '299855360243',
    projectId: 'grocery-3b0f8',
    databaseURL: 'https://grocery-3b0f8-default-rtdb.firebaseio.com',
    storageBucket: 'grocery-3b0f8.appspot.com',
    iosBundleId: 'com.example.grocery',
  );
}
